appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bjpvgZgieeAITnVelKI+kzu3LHCwpA344cqE00wUWk0YRsX/JFydkNBasnq8v9DFa6byVqbiDhdaDRJQnIH0rpCKv1o04fYdMW1vPx49XbdQzAPd8xPHMeDaPcyjEHFis3Zjd9WNgIdz3VPyVhcD8MWhk9WieVm2zpt0K1oYAKCA3KOT1CIHexYrpDVu0PYVCN0zo5rFfhPm7K/YB+T8H7iuSKME2Q8DX1YADL9cok8gGcgpSD8JtiUTHqYUPl2J8v19QWM5786YQIak5kZtgr+IgpzSzF+e/qei2SCfWVOwMZ4yAfAwH16tKnFxzD0FvmAMjlZ2/SNlOq5QJXqnjDIBEXV6MvHaAyfwdZCNde/8QaxRXQ4MK48d3nvKjsQNX6D1+DPx6DTCSs9bT4IkFVrcWWTA7jCCf/xGv3qxQjog7J1OL+Gh1AH4t4QK+2r5p3h3nOEK2gJQnvS/Ry4LVrX5Rec8KIQLVUA3jF4mss147pOyLmw8ez3ClUDXWXKugG4gOW/mBg/an3Q23uvPFiQ7AsSUKuQHXQhlOmG5/VPMgSglWXtm7Rnc75Sc2gF9znxrYu+B4xuwo2mezcojusfZrWecJTd/cRTuwbMYNrDA5I2P1KXjjCCzpZJ6iTv5IxdJJhMbDyZNF+ziOfGS+vYAAjYKiLERCKa7iYGauTk=
